language: python
python:
    - "2.6"
    - "2.7"
script:
    - python debug.py
notifications:
  email:
    recipients:
      - wwin3286tw@gmail.com
      - wwin3286tw@yahoo.com.tw
    on_success: always
    on_failure: always
